version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      # Install dependencies needed for running tests
      - pip install -r youssef/requirements.txt

  pre_build:
    commands:
      # Discover and run unit tests. For more information, see <https://docs.djangoproject.com/en/2.0/topics/testing/overview/>
      - echo 'test start'
      - python youssef/manage.py test

artifacts:
  files:
    - 'youssef/**/*'
